# -*- coding: utf-8 -*-
"""E-commerce Revenue Leakage & Return Optimization Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hN5evRk3HHx7P2LNw0EofsGVihD_CNZN
"""

import pandas as pd

#  Load the files
orders= pd.read_csv("olist_orders_dataset.csv")

orders.head()

print(orders['order_status'].value_counts())

print(orders.isnull().sum())

#  Load the files
items  = pd.read_csv("olist_order_items_dataset.csv")

items.head()

merged_data = pd.merge(orders, items, on='order_id', how='left')

# Calculate the 'Financial Struggle'
# We filter for 'canceled' and then sum the 'price' column
cancelled_value = merged_data[merged_data['order_status']== 'canceled']['price'].sum()

print(f"Total Revenue Lost to Canceled Orders: ${cancelled_value:,.2f}")

#  Check for 'Hidden' Losses (Unavailable orders)
unavailable_value = merged_data[merged_data['order_status'] == 'unavailable']['price'].sum()
print(f"Total Revenue Lost to Unavailable Orders: ${unavailable_value:,.2f}")

from google.colab import files
uploaded=files.upload()

#  Load the Product details
products = pd.read_csv('olist_products_dataset.csv')

# Merge our existing data with the products table
# We use 'product_id' as the glue this time
final_df = pd.merge(merged_data, products, on='product_id', how='left')

# Find the "Problem Categories"
# Let's see which categories have the most 'canceled' orders
problem_categories = final_df[final_df['order_status'] == 'canceled']['product_category_name'].value_counts()

print("--- Top 5 Categories with Canceled Orders ---")
print(problem_categories.head(5))

from google.colab import files
uploaded=files.upload()

# 1. Load the translation file
translation = pd.read_csv('product_category_name_translation.csv')

# 2. Merge it into your final dataframe
# This adds a new column called 'product_category_name_english'
final_df = pd.merge(final_df, translation, on='product_category_name', how='left')

# 3. Now calculate the Canceled counts using the ENGLISH names
english_problem_cats = final_df[final_df['order_status'] == 'canceled']['product_category_name_english'].value_counts()

print("--- Top 5 Problem Categories (English) ---")
print(english_problem_cats.head(5))

# 1. Count Total Orders per Category
total_per_cat = final_df['product_category_name'].value_counts()

# 2. Count Canceled Orders per Category
canceled_per_cat = final_df[final_df['order_status'] == 'canceled']['product_category_name'].value_counts()

# 3. Calculate the Percentage
cancel_rate = (canceled_per_cat / total_per_cat) * 100

# 4. Sort to see the highest percentage first
print("--- Categories with Highest CANCELLATION RATE (%) ---")
print(cancel_rate.sort_values(ascending=False).head(10))

from google.colab import files
uploaded=files.upload()

# 1. Load the Reviews
reviews = pd.read_csv('olist_order_reviews_dataset.csv')

# 2. Merge reviews with our final_df
# Note: One order can sometimes have multiple reviews, so we join on order_id
final_with_reviews = pd.merge(final_df, reviews, on='order_id', how='left')

# 3. The "Smoking Gun" Analysis:
# Let's compare the Average Review Score for 'delivered' vs 'canceled' orders
avg_scores = final_with_reviews.groupby('order_status')['review_score'].mean()

print("--- Average Review Score by Order Status ---")
print(avg_scores)

# 1. Create a summary of every product
product_summary = final_with_reviews.groupby('product_id').agg({
    'order_id': 'count',           # Total times ordered
    'price': 'sum',                # Total revenue
    'review_score': 'mean',        # Average happiness
    'order_status': lambda x: (x == 'canceled').sum() # Total cancels
})

# 2. Rename columns to make them clear
product_summary.columns = ['total_orders', 'total_revenue', 'avg_review', 'cancel_count']

# 3. Filter for products with at least 5 orders (to avoid random one-offs)
# and sort by the most cancels
hit_list = product_summary[product_summary['total_orders'] >= 5].sort_values(by='cancel_count', ascending=False)

print("--- THE HIT LIST: Top 5 Revenue Killers ---")
print(hit_list.head(5))

# --- THE LOAD STEP ---
# This saves your final, cleaned, and merged data into a single 'Master File'
final_with_reviews.to_csv('cleaned_ecommerce_master.csv', index=False)

print("Pipeline Complete! Cleaned master file saved as 'cleaned_ecommerce_master.csv'")

